; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
 
[platformio]
globallib_dir = ./include/lib
boards_dir = ./boards

[env:esp32-s3-devkitc-1]
platform = espressif32@6.6.0
board = lilygo-t-displays3
framework = arduino

upload_speed =  115200
monitor_speed = 115200
upload_port = COM11

build_flags = 
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DLV_CONF_INCLUDE_SIMPLE
    -DARDUINO_USB_CDC_ON_BOOT=1
    ;-DDISABLE_ALL_LIBRARY_WARNINGS
    -DARDUINO_USB_MODE=1
    ; Choose different options according to different driver chips
    ; Early use of CST328
    ;-DTOUCH_MODULES_CST_MUTUAL
    ; Use CST816 by default
    ; -DTOUCH_MODULES_CST_SELF      
    -DBOARD_HAS_PSRAM
    -I../libraries/merlinIncludes


monitor_filters =
	esp32_exception_decoder
	default

;board_build.arduino.memory_type = opi_qspi ;
board_build.filesystem = spiffs
board_build.partitions = default_16MB.csv  ; Adjust based on your board size    

;lib_ldf_mode = off ;deep+
lib_extra_dirs = 
    ../libraries/merlinIncludes
    ./include/lib


lib_deps =  
    FS
    SPIFFS
    bblanchon/ArduinoJson @ ^6.20.0    
	knolleary/PubSubClient@^2.8
    https://github.com/mathertel/OneButton @ ^2.0.4
	https://github.com/taranais/NTPClient
	PaulStoffregen/Time
    ;https://github.com/Bodmer/TFT_eSPI ;<-- DO NOT USE
    ;https://github.com/leethomason/tinyxml2
    https://github.com/fbiego/ESP32Time
    ;https://github.com/tzapu/WiFiManager
    lvgl/lvgl @ ^8.3.0-dev
    https://github.com/mmMicky/TouchLib
